# For details see:
# https://gitlab.invenia.ca/invenia/gitlab-ci-helper/-/blob/master/examples/julia.yml
---
include:
  - project: invenia/gitlab-ci-helper
    file: /templates/julia.yml

# Only include 64-bit jobs; research typically involves high memory machines anyway
variables:
  platform: "x86_64"  # 64-bit

# If you need to install system packages, such as `unzip`, you can do so as follows:
#.test:
#  before_script:
#    - echo "$ci_init" > ci_init && source ci_init && rm ci_init
#    - package_install unzip
